version: '3'
services:
  db:
    image: postgres:15.3-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30

  backend:
    build: ./backend/
    container_name: llm-backend
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    volumes:
      - ./backend:/llm/backend
    ports:
      - "8080:8080"
    tty: true

  frontend:
    build: ./frontend/llm-frontend
    volumes:
      - ./frontend:/llm/frontend
      - /llm/frontend/node_modules
    ports:
      - "3000:3000"
    tty: true

volumes:
  postgres_data: